### ISSUE TITLE
Handel-codepipeline delete fails with pipeline that doesn't have webhook

### ISSUE THREAD

**Issue by saholman** [byu-oit/handel-codepipeline#126]
Handel-codepipeline delete fails when the pipeline that is being deleted was created by an older version of handel-codepipeline.

**Comment by saholman** [comment]
```✓ jgubler-MacBook-Pro:node-oracle-lambda $ handel-codepipeline delete
info:    Welcome to the Handel CodePipeline deletion wizard
? Please enter the name of the pipeline from your handel-codepipeline.yml file that you would like to delete dev
? Please enter the name of the account for the pipeline you wish to delete dev-oit-byu
error:   Error deleting Handel CodePipeline: WebhookNotFoundException: null
error:    message=null, stack=WebhookNotFoundException: null
    at Request.extractError (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/sequential_executor.js:115:18), code=WebhookNotFoundException, name=WebhookNotFoundException, time=Tue Jun 19 2018 14:58:42 GMT-0600 (MDT), requestId=8c75bb98-7403-11e8-857f-d3d308c40c45, statusCode=400, retryable=false, retryDelay=53.33867850891949```

**Comment by saholman** [comment]
Another issue with deleting: ```
[Container] 2018/06/20 14:49:09 Running command handel-codepipeline $ACTION --pipeline $PIPELINE --secrets $SECRETS --account_name $ACCOUNT
[31merror[39m:   Error deleting Handel CodePipeline: ValidationException: Action with name GitHub was not found in the first stage of pipeline oauth-token-lambda-dev
[31merror[39m:    message=Action with name GitHub was not found in the first stage of pipeline oauth-token-lambda-dev, stack=ValidationException: Action with name GitHub was not found in the first stage of pipeline oauth-token-lambda-dev
    at Request.extractError (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/handel-codepipeline/node_modules/aws-sdk/lib/sequential_executor.js:115:18), code=ValidationException, name=ValidationException, time=Wed Jun 20 2018 14:49:10 GMT+0000 (UTC), requestId=1773988c-7499-11e8-91cf-595e24218f18, statusCode=400, retryable=false, retryDelay=77.97413961375364

[Container] 2018/06/20 14:49:10 Phase complete: BUILD Success: true
[Container] 2018/06/20 14:49:10 Phase context status code:  Message: 
[Container] 2018/06/20 14:49:10 Entering phase POST_BUILD
[Container] 2018/06/20 14:49:10 Phase complete: POST_BUILD Success: true
[Container] 2018/06/20 14:49:10 Phase context status code:  Message: 
```

**Comment by saholman** [comment]
Also, when these are happening inside of the codebuild for the bot the codebuild is still succeeding.  If handel-codepipeline fails, can we have it exit with a non-zero exit code so that the build fails rather than just print the error?

**Comment by saholman** [comment]
@ndpete It looks like handel-codepipeline is looking for a stage with name='github' instead of type='github' and that is causing the above error.  We get a similar error when deploying a handel-codepipeline and the name of the first stage isn't 'github'.

**Comment by saholman** [comment]
Perhaps here? https://github.com/byu-oit/handel-codepipeline/blob/81f1ec61b2ef94ed1dc32602c7e3a6deb268c73f/src/phases/github/index.ts#L121

**Comment by saholman** [comment]
See https://github.com/byu-oit/handel-codepipeline/pull/127

**Comment by dsw88** [comment]
I believe this should be fixed in the most recent version of handel-codepipeline.
